=== NastyaSmielova/distributedComputing/PO_10_1/map.dtd
<?xml version='1.0' encoding='UTF-8'?> 
<!ELEMENT map ( country* )> 
<!ELEMENT country ( nameC, city* )> 
<!ATTLIST country id CDATA  #REQUIRED>
<!ELEMENT nameC ( #PCDATA )>
<!ELEMENT count ( #PCDATA )> 
<!ELEMENT city ( name, iscap, count )> 
<!ATTLIST city id CDATA  #REQUIRED>
<!ELEMENT iscap (#PCDATA)> 
<!ELEMENT name (#PCDATA)>

=== NastyaSmielova/distributedComputing/PO_10_1/map2.xml
<?xml version="1.0" encoding="WINDOWS-1251" standalone="no"?><!DOCTYPE map PUBLIC "map" "map.dtd">
<map><country id="10"><nameC>Ukraine</nameC><city id="12"><name>Kyiv </name><iscap>true</iscap><count>5000</count></city><city id="52"><name>Lviv</name><iscap>false</iscap><count>800</count></city><city id="3"><name>Kharkiv</name><iscap>false</iscap><count>4000</count></city></country><country id="2"><nameC>USA</nameC><city id="4"><name>Washington </name><iscap>true</iscap><count>300000</count></city><city id="5"><name>New York </name><iscap>false</iscap><count>400000</count></city></country><country id="37"><nameC>Canade</nameC><city id="6"><name>Ottava </name><iscap>true</iscap><count>40000</count></city><city id="7"><name>Toronto</name><iscap>false</iscap><count>30000</count></city></country></map>
